### ISSUE TITLE
TypeError: 'NoneType' object is not callable for basic example

### ISSUE THREAD

**Issue by arnavdas88** [swimlane/pyattck-data#81]
## Describe the bug

When executing the basic example from https://pyattck.readthedocs.io/en/latest/ics/icsattck.html, an Exception is thrown.

## To Reproduce

```python
>>> from pyattck import Attck
>>> attack_mitre = Attck()
>>> technique_list = attack_mitre.ics.techniques
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck/attck.py", line 289, in ics
    from .ics import ICSAttck
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck/ics.py", line 7, in <module>
    class ICSAttck(Base):
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck/ics.py", line 42, in ICSAttck
    __attck = MitreAttck(**Base.config.get_data("ics_attck_json"))
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck_data/attack.py", line 55, in __init__
    raise te
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck_data/attack.py", line 53, in __init__
    self.__attrs_init__(**kwargs)
  File "<attrs generated init pyattck_data.attack.MitreAttck>", line 14, in __attrs_init__
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck_data/attack.py", line 66, in __attrs_post_init__
    raise te
  File "/home/jan/.local/lib/python3.8/site-packages/pyattck_data/attack.py", line 62, in __attrs_post_init__
    data = TYPE_MAP.get(item['type'])(**item)
TypeError: 'NoneType' object is not callable
```

Referred in [Issue #125](https://github.com/swimlane/pyattck/issues/125) in [PyAttck](https://github.com/swimlane/pyattck) as well...

## Expected behavior

No error

## Reason

It seems like the past month was released a new STIX object. The [campaigns](https://attack.mitre.org/campaigns/)

What I found is that is not yet implemented on the pyattck-data lib.
https://github.com/swimlane/pyattck-data/blob/e704a5c46d916ee3fb898b8c16902d8e7035fbe4/src/pyattck_data/attack.py#L27

(- by @kastellanos)

**Comment by SirSkizo** [comment]
Related to [question](https://stackoverflow.com/questions/75012181/impossible-to-retrieve-data-form-pyattck-module)
